######################################################################
##  Good night Routine
######################################################################

- alias: 'Good Night Trigger'
  trigger:
    - platform: state
      entity_id: input_boolean.good_night
      to: 'on'
      from: 'off'
    - platform: state
      entity_id:
        - binary_sensor.sleepnumber_craig_craig_is_in_bed
        - binary_sensor.sleepnumber_craig_lisa_is_in_bed
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.sleepnumber_craig_craig_is_in_bed
          state: 'on'
        - condition: state
          entity_id: person.craig
          state: 'not_home'
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.sleepnumber_craig_lisa_is_in_bed
          state: 'on'
        - condition: state
          entity_id: person.lisa
          state: 'not_home'

  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_night
    - service: light.turn_off
      entity_id:
        - light.family_room_lamp
        - light.upstairs_tv_room_3
        - light.closest_to_front_door
        - light.closest_to_laundry
        - light.upstairs_tv_room_2
        - light.upstairs_tv_room_1
        - light.bathroom
        - light.lamp_on_lisas_side
        - light.lamp_on_craigs_side
        - light.fireplace
    - service: switch.turn_off
      entity_id:
        - switch.012008286001949488f8
        - switch.backyardpartylights
        - switch.garage_light
#        - switch.front_porch_fountain
    - service: cover.close_cover
      entity_id:
        - cover.back_kitchen_windows
        - cover.all_shades

#   - service: script.interior_off
#
#    - service: script.speech_engine
#      data_template:
#        value1: >
#          {{ [
#          "Sleep Tight, Don't let the bedbugs bite.",
#          "Have pleasant dreams",
#          "As they say in the Navy, See you in the rise."
#          "Dream pleasant dreams.  Tomorrow is a new day.",
#          "Early sleep and early wake up gives health and makes you grow.",
#          "Good night, good night! Parting is such sweet sorrow that I shall say goodnight till it is Morrow.",
#          "This good night isn’t meant to bring an end to this day. It’s intended to wish you awesomeness in what lies ahead.",
#          "Stuff your worries in your pillow, wrap your troubles in your blanket and spread your anxieties on your sheets. When you wake up tomorrow, you may have dirty linen, but more importantly, you’ll have a fresh mind and a happy heart. Good night.",
#          "Goodnight, talk to you tomorrow. ",
#          "Goodnight sweetheart. ",
#          "Go to bed, you sleepy head! ",
#          "Nighty Night. ",
#          "Sleep snug as a bug in a rug! ",
#          "Lights out! ... Uh huh. ... Dance, dance dance. ",
#          "Time to ride the rainbow to dreamland! ",
#          "Sweet dreams. ",
#          "See ya' in the mornin'! ",
#          "I-ill be right here when you wake up. moo ahh .. ha .. ha ",
#          "I-ill be dreaming of your face! ",
#          "You're the most wonderful user in the whole world! ",
#          "I'm yours, forever and always. ",
#          "Parting is such sweet sorrow, that I shall say good night till it be tomorrow. ",
#          "Can you hear that? ... Its your soft warm bed calling your name. You really must go and see what it wants. ",
#          "Grumpy cat says goodnight.",
#          "Goodnight, sweet dreams. ",
#          "You have so much to be greatful for... goodnight.",
#          "Wishing you a goodnight and sweatest dreams.",
#          "What about good night kisses? "
#          ] | random }}
