### I just use this to test different iOS push notifications

- alias: Notify iOS app
  trigger:
    platform: time
    at: '17:49:00'
  action:
    - service: script.notify_engine
      data_template:
        title: 'Casa Del Vino Alert'
        value1: 'Make today great day!'
        who: 'craig'

#  action:
#    service: notify.ios_craigiphonex
#    data:
#      title: "Smart Home Alerts"
#      message: "Casa Del Vino says - I hope you had a great day!"
