#########
# Audio Notifications
########

        ##########################################################
        ## Welcome Home Lisa Audio Greeting
        ##########################################################

- alias: Notification Audio - Welcome Home Lisa

  trigger:
    - platform: state
      entity_id: cover.lisa_garage
      from: "closed"
      to: "open"

  condition:
    - condition: state
      entity_id: person.lisa
      state: 'home'
    - condition: state
      entity_id: input_boolean.lisa_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: time
      after: '07:00'
      before: '22:00'

  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_garage
      data:
        volume_level: '0.5'
    - delay: '00:01:00'
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.sonos_garage
        message: "Welcome home Lisa."

        ##########################################################
        ## Welcome Home Amanda Audio Greeting
        ##########################################################

- alias: Notification Audio - Welcome Home Amanda

  trigger:
    - platform: state
      entity_id: person.amanda
      from: "not_home"
      to: "home"
      for: "00:03:00"

  condition:
    - condition: state
      entity_id: input_boolean.amanda_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: time
      after: '07:00'
      before: '21:00'

  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_family_room_2
      data:
        volume_level: '0.4'
    - delay: '00:02:00'
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.sonos_family_room_2
        message: "Welcome home Amanda. We are glad you are here."

        ##########################################################
        ## Welcome Home Phil Audio Greeting
        ##########################################################

- alias: Notification Audio - Welcome Home Phil

  trigger:
    - platform: state
      entity_id: device_tracker.phillips_iphone
      from: 'away'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.phil_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: time
      after: '07:00'
      before: '21:00'

  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_family_room_2
      data:
        volume_level: '0.4'
    - delay: '00:03:00'
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.sonos_family_room_2
        message: "Welcome to Casa Del Vino Phil. We are glad you are here."

        ##########################################################
        ## Welcome Home David Audio Greeting
        ##########################################################

- alias: Notification Audio - Welcome Home David

  trigger:
    - platform: state
      entity_id: person.david
      from: "not_home"
      to: "home"
      for: "00:01:00"

  condition:
    - condition: state
      entity_id: input_boolean.david_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_family_room_2
      data:
        volume_level: '0.4'
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.sonos_family_room_2
        message: "Welcome to Casa Del Vino David. But, Damnit David. Quit drinking all of the beer. Go get you some more pokey men."

        #################################################################
        ## Lisa Left Work Audio Notification
        #################################################################

#- alias: Notification Audio - Lisa Left Work
#
#  trigger:
#    - platform: state
#      entity_id: person.lisa
#      from: 'Lisa Work'
#      to: 'away'
#
#  condition:
#    - condition: state
#      entity_id: device_tracker.craigiphonex
#      state: 'home'
#    - condition: state
#      entity_id: person.lisa
#      state: 'away'
#    - condition: state
#      entity_id: input_boolean.lisa_away
#      state: 'on'
#    - condition: state
#      entity_id: input_boolean.disable_notifications
#      state: 'off'
#    - condition: time
#      after: '09:00'
#      before: '22:00'
#
#  action:
#    - service: sonos.snapshot
#      data:
#        with_group: yes
#    - delay: '00:00:03'
#    - service: sonos.unjoin
#      entity_id:
#        - media_player.sonos_garage
#        - media_player.sonos_kitchen
#        - media_player.sonos_kitchen_2
#        - media_player.sonos_wine_room
#        - media_player.sonos_upstairs
#    - delay: '00:00:01'
#    - service: sonos.join
#      data:
#        master: media_player.sonos_kitchen
#      entity_id:
#        - media_player.sonos_kitchen
#        - media_player.sonos_kitchen_2
#        - media_player.sonos_garage
#        - media_player.sonos_wine_room
#        - media_player.sonos_upstairs
#    - delay: '00:00:01'
#    - service: media_player.volume_set
#      entity_id:
#        - media_player.sonos_kitchen
#        - media_player.sonos_kitchen_2
#        - media_player.sonos_garage
#        - media_player.sonos_wine_room
#        - media_player.sonos_upstairs
#      data:
#        volume_level: '0.6'
#    - delay: '00:00:02'
#    - service: tts.amazon_polly_say
#      data_template:
#        entity_id: media_player.sonos_kitchen
#        message: "Lisa has left work, and will arrive Home in about, {{states('sensor.lisa_to_home')}} minutes"
#    - delay: '00:00:25'
#    - service: sonos.restore
#      data:
#        with_group: yes


      ##########################################################
      ## Good Morning Everyone the sun has risen Audio Greeting
      ##########################################################

#- alias: Notification Audio - Welcome to a new day

#  trigger:
#    - platform: sun
#      event: sunrise
#      offset: "+00:01:00"

#  condition:
#      entity_id: group.family
#      state: 'home'
#    - condition: state
#      entity_id: group.bed
#      state: 'off'
#    - condition: state
#      entity_id: input_boolean.disable_notifications
#      state: 'off'

#  action:
#    - service: media_player.volume_set
#      entity_id:
#        - media_player.sonos_family_room_2
#      data:
#        volume_level: '0.2'
#    - delay: '00:00:02'
#    - service: tts.amazon_polly_say
#      data_template:
#        entity_id: media_player.sonos_family_room_2
#        message: "Good morning Craig and Lisa. Make today a great day! "

    ##########################################################
    ## Send message at a specific time. Last used for - Happy Birthday David
    ##########################################################

# - alias: Notification Audio - Happy Birthday David

#  trigger:
#    - platform: time
#      at: '19:00:00'

#  condition:
#    - condition: state
#      entity_id: group.family
#      state: 'home'
#    - condition: state
#      entity_id: group.bed
#      state: 'off'
#    - condition: state
#      entity_id: input_boolean.disable_notifications
#      state: 'off'

#  action:
#    - service: sonos.snapshot
#      data:
#        with_group: yes
#    - delay: '00:00:03'
#    - service: sonos.unjoin
#      entity_id:
#        - media_player.sonos_family_room_2
#        - media_player.sonos_garage
#        - media_player.sonos_kitchen
#        - media_player.sonos_kitchen_2
#        - media_player.sonos_wine_room
#        - media_player.sonos_upstairs
#    - delay: '00:00:01'
#    - service: sonos.join
#      data:
#        master: media_player.sonos_kitchen
#      entity_id:
#        - media_player.sonos_family_room_2
#        - media_player.sonos_kitchen
#        - media_player.sonos_kitchen_2
#        - media_player.sonos_garage
#        - media_player.sonos_wine_room
#        - media_player.sonos_upstairs
#    - delay: '00:00:01'
#    - service: media_player.volume_set
#      entity_id:
#        - media_player.sonos_family_room_2
#        - media_player.sonos_kitchen
#        - media_player.sonos_kitchen_2
#        - media_player.sonos_garage
#        - media_player.sonos_wine_room
#        - media_player.sonos_upstairs
#      data:
#        volume_level: '0.6'
#    - delay: '00:00:02'
#    - service: tts.amazon_polly_say
#      data_template:
#        entity_id: media_player.sonos_kitchen
#        message: "Hello David. We all wish you a happy fiftyith birthday. Have a great day. Lets all take a moment and salute Davids hero, Speed Racer. Now, will someone please pour me some more wine?"
#    - delay: '00:00:25'
#    - service: sonos.restore
#      data:
#        with_group: yes
