######################################################################
##  Routines that happen at sunset.
######################################################################

- alias: Turn on the light switches when the sun sets
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    service: switch.turn_on
    entity_id:
      - switch.front_porch
      - switch.back_patio
      - switch.012008286001949488f8
      - switch.backyardpartylights

- alias: Turn on the lights when the sun sets
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    service: light.turn_on
    entity_id:
      - light.family_room_lamp
      - light.upstairs_tv_room_3
      - light.closest_to_front_door
      - light.closest_to_laundry
      - light.upstairs_tv_room_2
      - light.upstairs_tv_room_1
      - light.bathroom
      - light.lamp_on_lisas_side
      - light.lamp_on_craigs_side
      - light.fireplace
      - light.front_porch_yeelight
